version: '3'
services:
  angular-app:
    build:
      context: C:\Users\madhusuthananm\AngularProjects\NewDockerHelloApp
      dockerfile: Dockerfile
    ports:
      - "1600:80"

  dotnet-app:
    build:
      context: E:\angularsite\HelloWorldFRONT+BACK\HelloWorldBackEndC#\HelloWorld
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SA_PASSWORD: "Msbeiber@63"
      ACCEPT_EULA: "Y"
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Msbeiber@63"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
